import React from 'react';
import Layout from '../../components/auth/layout/Layout';

const Contact = () => {
    return (
        <div>
            <div><Layout/></div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta tempore fuga doloremque quo accusamus iusto nisi incidunt eos sequi nostrum, quas qui aliquid ut quod placeat! Ex, error fuga sed natus id saepe fugit obcaecati impedit dolor harum numquam repudiandae sint repellendus a architecto unde aperiam nihil ut minus facilis suscipit! Nam exercitationem doloribus eos quam possimus corrupti officia eligendi vitae iusto sapiente temporibus accusamus soluta commodi blanditiis, a consequatur voluptate deleniti aperiam voluptates reiciendis quidem nobis asperiores, sunt rem. Temporibus tenetur reprehenderit et non sint, alias iste! Facere dignissimos repudiandae recusandae ea odit illo facilis officiis eveniet odio. Aperiam laboriosam praesentium alias, modi doloribus magnam est culpa vel labore molestiae quisquam similique unde, sed quam eaque officia tempora aliquam quo in velit hic, accusantium sit libero? Quasi eos quod maiores assumenda, quaerat quos quae error ullam culpa dicta amet quam autem reiciendis saepe perspiciatis eveniet et reprehenderit magnam officiis. Assumenda repellat magnam officiis sed dolorum consequuntur, quia reiciendis nobis rem mollitia facere et velit quaerat rerum. Numquam qui tempora laborum hic iure non esse, consequuntur dicta praesentium minima atque voluptates illum quisquam laboriosam. Dolores, beatae ratione, doloribus voluptate voluptas, doloremque animi temporibus error tenetur aperiam rerum tempora expedita in? Molestiae in dignissimos cupiditate facere ut aperiam incidunt voluptate sapiente aliquid excepturi recusandae quos maiores quas sint dolorum, pariatur eos dolore delectus explicabo! Temporibus quis ab saepe necessitatibus, libero, exercitationem inventore perferendis nobis labore atque vitae eius enim eaque illo voluptate hic? Cumque nam dolorum officiis. Alias quas nobis provident similique? Magnam quaerat eum voluptatem, iusto expedita quae. Magnam a nostrum voluptates placeat eveniet reiciendis architecto repellat non obcaecati! Architecto dolores rem repudiandae alias totam inventore reprehenderit nulla doloremque mollitia officiis ad, cumque quasi. Vitae tempore sit voluptates molestias consequatur! Quis animi aliquam ipsam vitae ad incidunt explicabo deleniti nam.</div>
        </div>
    );
};

export default Contact;